import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <header className="fixed top-0 left-0 w-full z-50">
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4
        backdrop-blur-md bg-white/60 dark:bg-black/40 border-b border-white/20 dark:border-white/10
        shadow-sm"
      >
        {/* Logo */}
        <div className="text-lg font-semibold tracking-tight">
          Baobei inc<span className="text-blue-500">.</span>
        </div>

        {/* Links */}
        <div className="hidden md:flex items-center gap-8 text-sm">
          <a href="/" className="hover:text-blue-500 transition">Jan</a>
          <a href="/feb" className="hover:text-blue-500 transition">Feb</a>
          <a href="/march" className="hover:text-blue-500 transition">March</a>
          <a href="/april" className="hover:text-blue-500 transition">April</a>
          <a href="/may" className="hover:text-blue-500 transition">May</a>
          <a href="/june" className="hover:text-blue-500 transition">June</a>
          <a href="/july_aug" className="hover:text-blue-500 transition">July/August</a>
        </div>

      </nav>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />

        {/* spacing so content doesn't hide behind fixed navbar */}
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}